README.md

The first rename missed the `README.md` file, which this fixes

Fix remaining `protobuf-wire` name references

---

src/Proto3/Suite/DotProto/AST.hs

The `Proto3.Suite.DotProto.AST` module has several `arbitraryXXX`
functions at the bottom of the module which could be made into
`Arbitrary` instances for their respective types.  This change
refactors the module to create `Arbitrary` instances for as many
types as possible.
This refactor is behavior-preserving, meaning that some of these
`Arbitrary` instances are not as arbitrary as they could be.  For
example, some of the instances return fields that are always an
empty string when they could be arbitrary strings.  This is because
this was the original behavior of the corresponding `arbitraryXXX`
function.
I also try to avoid using operators as much as possible and use `do`
notation wherever possible.

Transform QuickCheck code into `Arbitrary` instances

---

nix/proto3-wire.nix

I shouldn't have used the SSH URL for the repo ref to `proto3-wire`. This PR fixes that.

Fix proto3-wire url used by `fetchgit`

---

release.nix
tests/TestCodeGen.hs
tests/decode.sh
tests/encode.sh
tests/tests.patch

This PR fixes the way that code generation tests are run. The pattern is now the same as `grpc-haskell`: we use the custom `ghc` which has the `proto3-suite` and its dependencies included.
After this change, `nix-shell release.nix proto3-suite.env` produces an environment where all of the unittests can be run interactively and iteratively without any by-hand tweaking, which was not the case before.
Also adds `proto3-suite-linux` and `proto3-suite-darwin` toplevel attrs.

Ensure CG tests succeed during `nix-build` and `nix-shell` via `cabal`

---

proto3-suite.cabal

It's needed to build with stack nightly.

Increase upper bound of the 'vector' dependency.

---

tests/SimpleDecodeDotProto.hs
tests/SimpleEncodeDotProto.hs
tests/check_simple_dot_proto.py
tests/send_simple_dot_proto.py

This PR makes it so that, e.g.
```bash
[nix-shell]$ mkdir -p test-files/py-tmp
[nix-shell]$ export PYTHONPATH=$PYTHONPATH:$(pwd)/test-files/py-tmp
[nix-shell]$ protoc --python_out=test-files/py-tmp test-files/test.proto
[nix-shell]$ protoc --python_out=test-files/py-tmp test-files/test_import.proto
[nix-shell]$ touch test-files/py-tmp/test_files/__init__.py
[nix-shell]$ python tests/send_simple_dot_proto.py | python tests/check_simple_dot_proto.py
```
will succeed, whereas before only the haskell encoder => python decoder and python encoder => haskell decoder paths could be exercised.

Use identical test values in python codec test scripts

---

tests/Main.hs
tests/TestCodeGen.hs

As I'm about to start exercising code generation over `deriving Generic` in some of the tests, I wanted to make a minor cleanup pass. The majority of the changes consist of regrouping and making labels for tests a bit more consistent.
NB: This PR is against the `joel-prefer-codegen-over-derive-generic` branch, not `master`. I'll be submitting PRs against that branch in the near term to facilitate incremental reviews.

Misc cleanup/refactor pass on test suite descriptions and structure

---

src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Parsing.hs

The individual commits should be self explanatory, but here's the gist:
- Demote fatal error about `oneof`'s unimplemented state in the code generator to a loud warning; that support is coming soon and it may be useful to be able to process input .protos which use the construct.
- CG: Emit parens around negative integral lits
- CG: Use qualified import for `GHC.Enum` and `GHC.Generics`
- Parser: Resolve ambiguity in `rpcClause` parser
- Parser: Improve comment stripping

Fix misc parsing/CG bugs

---

tools/canonicalize-proto-file/Main.hs

GHC 8.2 became more restrictive when checking default signatures, demanding an
explicit equality constraint here. See also:
https://github.com/ekmett/lens/issues/712
Referenced there:
https://ghc.haskell.org/trac/ghc/ticket/13258
https://ghc.haskell.org/trac/ghc/ticket/13249

Fix `CanonicalRank` default signature for GHC 8.2

---

proto3-suite.cabal

QuickCheck 2.10 moves some instances to the `quickcheck-instances` package, notably for `Natural`.
This is mostly a heads-up, I'd also be happy to provide a CPP'd patch if you'd prefer that.

Tighten upper bound on QuickCheck

---

src/Proto3/Suite/DotProto/Generate.hs
test-files/test_proto_oneof.proto
tests/TestProtoOneof.hs
tests/TestProtoOneofImport.hs

We were incorrectly ordering pattern binders: pattern binders for normal fields came first, followed by pattern binders for oneof fields. The correct behavior is to order the pattern binders in syntactic order of their occurrence in the protobuf type definition (which is the same as the record field order in the corresponding generated Haskell type).
Also adds some additional tests and includes some misc improvements and some light refactoring/renames.

Fix pattern binder order bug in JSONPB instance generation for oneof

---

src/Proto3/Suite/DotProto/Generate.hs
tests/TestCodeGen.hs

The main reason for this change is so that we can use `Generic`-based introspection to recover the original enum field names from generated datatypes (e.g., via the `Finite` typeclass), which is important for JSONPB encoding, among other things.
This PR also resolves issue https://github.com/awakesecurity/proto3-suite/issues/22.

Use protobuf enum field names as they occur in `.proto` files

---

src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/JSONPB.hs
src/Proto3/Suite/JSONPB/Class.hs
tests/TestProto.hs
tests/TestProtoImport.hs
tests/TestProtoOneof.hs
tests/TestProtoOneofImport.hs

The preliminary JSONPB implementation only provided the `toEncoding`-like typeclass method, `toEncodingPB`, because we didn't think it was useful to render protobuf values to the `Data.Aeson.Value` intermediate representation.
However, it's become apparent that this was an oversight, as we would like to generate `aeson` instances in terms of the the JSONPB instances, and be able to use other packages (e.g. `aeson-pretty`) which rely on the `Data.Aeson.Value` IR.
This PR adds the `toJSONPB` function (analogous to `aeson`'s `toJSON`) to the `ToJSONPB` typeclass, and makes corresponding changes to code generation to provide implementations of the new function.

Provide a `toJSONPB` analog to `Data.Aeson.toJSON`

---

src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/JSONPB.hs
src/Proto3/Suite/JSONPB/Class.hs
tests/TestProto.hs
tests/TestProtoImport.hs
tests/TestProtoOneof.hs
tests/TestProtoOneofImport.hs

This PR extends the code generator to define `aeson` instances for protobuf types, in terms of their generated JSONPB instances. 
This change allows use of generated Haskell types in `aeson` contexts without additional boilerplate.

Generate `aeson` instances for protobuf types

---

default.nix
nix/aeson-pretty.nix
nix/cabal-doctest.nix
nix/insert-ordered-containers.nix
nix/swagger2.nix
proto3-suite.cabal
release.nix
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Generate/Swagger.hs
src/Proto3/Suite/JSONPB.hs
stack.yaml
tests/TestProto.hs
tests/TestProtoImport.hs
tests/TestProtoOneof.hs
tests/TestProtoOneofImport.hs

This PR implements preliminary [`swagger2`](https://hackage.haskell.org/package/swagger2-2.1.6) schema generation for JSONPB encodings of protobuf types.
E.g., given:
```
message MultipleFields {
double multiFieldDouble = 1;
float  multiFieldFloat  = 2;
int32  multiFieldInt32  = 3;
int64  multiFieldInt64  = 4;
string multiFieldString = 5;
bool   multiFieldBool   = 6;
}
```
We'll generate:
```
λ> ppSchema (Proxy @MultipleFields)
{
"type": "object",
"properties": {
"multiFieldInt64": {
"maximum": 9223372036854775807,
"format": "int64",
"minimum": -9223372036854775808,
"type": "integer"
},
"multiFieldString": {
"type": "string"
},
"multiFieldDouble": {
"format": "double",
"type": "number"
},
"multiFieldInt32": {
"maximum": 2147483647,
"format": "int32",
"minimum": -2147483648,
"type": …
```

Generate preliminary `swagger2` schemas for JSONPB encodings

---

src/Proto3/Suite/Class.hs
src/Proto3/Suite/DotProto/AST.hs
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Parsing.hs
src/Proto3/Suite/DotProto/Rendering.hs
test-files/test_proto.proto
tests/TestCodeGen.hs
tests/TestProto.hs

Currently only parses the options but does not use them in the generated code.
Additionally, this PR fixes type errors in the test suite introduced by #42

Parse options for enum types

---

src/Proto3/Suite/Types.hs

This fixes an inconvenience I just ran into trying to `fmap` over an `Enumerated` wrapper.

Derive more typeclasses for wrappers

---

README.md
release.nix
shell.nix
tests/generate-test-types.sh

This allows `nix-shell` to work without any arguments (and `cabal`'s
`nix: True` mode)

Add `shell.nix`

---

src/Proto3/Suite/DotProto/Generate.hs

Fixes https://github.com/awakesecurity/gRPC-haskell/issues/53
The motivation for this change is so that generated code does not need to
depend on the `grpc-haskell-core` package
This removes the unnecessary `Network.GRPC.HighLevel.Server.Unregistered`
import from the generated code since everything provided by the low-level
library is already re-exported by the high-level library
I tested this against the `gRPC-haskell` test suite, which still passed after this
change

Generated code no longer depends on `grpc-haskell-core`

---

src/Proto3/Suite/DotProto/Generate.hs

Fixes #60
The `Proto3.Suite.DotProto.Generate` module backported `liftEither` to a
local definition to support older versions of the `mtl` but was missing
a forwards-compatible CPP guard to avoid conflicting with the open import
of `Control.Monad.Except`

Fix `liftEither` definition to not conflict with open import

---

src/Proto3/Suite/DotProto/Generate/Swagger.hs

This fixes the generated field labels for sum types. Given the following message,
```
message MyMessage {
oneof FooOrBar {
Foo x = 1;
Bar y = 2;
}
}
```
The current `ToSchema` instance will generate a swagger schema like this:
```
{  "FooOrBar": {
"FooOrBarX": {...},
"FooOrBarY": {...}
}
}
```
The corrected schema looks like this:
```
{  "FooOrBar": {
"x": {...},
"y": {...}
}
}
```

Fix ToSchema field names for oneof types

---

src/Proto3/Suite/JSONPB.hs
src/Proto3/Suite/JSONPB/Class.hs

That didn't typecheck... and it turned out to be quite simple, so these functions are redundant.

Revert "Add JSONPB encoder/decoder for lazy Text"

---

.gitignore
proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/JSONPB.hs
src/Proto3/Suite/JSONPB/Class.hs
tests/ArbitraryGeneratedTestTypes.hs
tests/Main.hs
tests/TestCodeGen.hs
tools/canonicalize-proto-file/Main.hs

Before this change, we JSON-encoded omitted `oneof` fields (when the emit default values option is enabled) as `"keyname":{}`. After this change, the encoding is `"keyname":null` to be more consistent with encoding of omitted message fields elsewhere. 
Note that the wire encoding for both is the same; this is just to make the JSON encoding more consistent.

Make oneof default value encoding more consistent

---

nix/proto3-wire.nix
proto3-suite.cabal
src/Proto3/Suite/Class.hs
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Generate/Swagger.hs
src/Proto3/Suite/DotProto/Rendering.hs
src/Proto3/Suite/JSONPB/Class.hs
src/Proto3/Suite/Tutorial.hs
test-files/test_proto_oneof_import.proto
tests/Main.hs

This should speed up protobuf serde a bit (not sure by how much), by getting rid of the container traversals to wrap things in newtypes in `encodeMessage/decodeMessage`. 
Using unboxed proxy couples us to GHC, but that's ok because we only officially support GHC 8.0+. Because this changes the API for the `Named, Finite, Primitive` classes, the version has been bumped to `0.3.0.0`.

Use Data.Coerce.coerce and unboxed proxy

---

src/Proto3/Suite/DotProto/Generate.hs
tests/Main.hs

In #91 I preserved the old behaviour, but from #30 it seems that `Fixed` should really be applied along with the rest of the newtype wrappers and omitted from the Haskell type that fixed scalar types are translated to.

Don't render fixed scalar types with Fixed wrapper

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Internal.hs

Turtle uses \ for path separators on Windows, proto3-suite used splitOn "/" which didn't work, resulting in garbled paths and not capitalising things correctly. I solved that by moving to split isPathSeparator from the filepath library.
Fixes #93

Fix so paths are split properly on Windows

---

src/Proto3/Suite/Class.hs

Means that we never go near the Monad bits, so could potentially switch parser, or use faster instances.

Use the Applicative instance for the Parser

---

src/Proto3/Suite/DotProto/Generate.hs

It's super useful to have NFData available, and having an orphan instance is yuck, so this patch generates NFData instances for all suitable types.

Add NFData derivations on the generated code

---

src/Proto3/Suite/DotProto/Generate.hs

Before the test case in #97 generated:
```
((Hs.coerce @(Hs.Int64)
@(HsProtobuf.Signed (HsProtobuf.Fixed Hs.Int64)))
(HsProtobuf.ForceEmit y))
```
Now it generates:
```
HsProtobuf.ForceEmit
((Hs.coerce @(Hs.Int64)
@(HsProtobuf.Signed (HsProtobuf.Fixed Hs.Int64)))
y)
```
I'm assuming the ForceEmit is important, and that seemed like the only sensible place to put it. But I was totally guessing... I welcome feedback!

#97, make sure OneofSubfield generates well-typed code for non-Maybe

---

proto3-suite.cabal

Hackage rejects uploading any package with the `-Werror` flag since it
becomes likely to break due to non-breaking changes in dependencies

Remove `-Werror` flag

---

proto3-suite.cabal

This is the same as #101, except I realized that there was more than one
`-Werror` in the `proto3-suite.cabal` file

Remove more `-Werror`

---

src/Proto3/Suite/DotProto/Rendering.hs

When generating .proto source code or files,
indent 2 spaces within most nested constructs, such
as messages, instead of a variable amount depending
upon the keyword and name of the nested construct.
This change should improve readability by
reducing the typical amount of indentation.
Also fix rendering of multi-line comments.

Adjust indentation of generated .proto files.

---

proto3-suite.cabal
src/Proto3/Suite/Class.hs
src/Proto3/Suite/DotProto/AST.hs
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Internal.hs
src/Proto3/Suite/DotProto/Parsing.hs
src/Proto3/Suite/DotProto/Rendering.hs
tests/Main.hs
tools/canonicalize-proto-file/Main.hs
tools/compile-proto-file/Main.hs

Also, replace `Maybe String` with `String` as the way we note
comments in the AST.  The empty string renders as the absence of
a comment, whereas "\n" renders as an empty single-line comment.
Both of these changes modify the AST; therefore
we go to a new version of proto3-suite: 0.4.0.0.
This change also includes adaptations to support
multiple versions of GHC.

Render comments for messages, enums, and services.

---

proto3-suite.cabal

The tests seem to work fine with QuickCheck 2.13.2

Bump QuickCheck upper bound

---

nix/fetchNixpkgs.nix
nix/proto3-wire.nix
proto3-suite.cabal
release.nix

Revert to ca03aa9d846d88b0762e40f9588b4927de22f798
Commit e740674a4c70f3fb0bae34c8bff3c31c70359c77 was meant for a PR,
not for direct inclusion into master.

Revert accidental commit

---

proto3-suite.cabal

Relaxes semigroups version bounds on tests and makes them conditional on GHC>8.0
Done for [gRPC-haskell#97](https://github.com/awakesecurity/gRPC-haskell/issues/97)

Update dependencies for Stackage

---

src/Proto3/Suite/DotProto/Generate.hs
tests/TestCodeGen.hs
tools/compile-proto-file/Main.hs

When adding the new behavior for translating `protobuf` files to Haskell modules, we added a flag to keep the old behavior for backwards compatibility (the new behavior became the default). In this PR we are now completely removing that flag and completely removing the old behavior.

Remove useLegacyTypes flag that guards old behavior of compile-to-proto

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs

Hello. I currently ran into a couple of issues in terms of how I am using this project, and so I fixed them in my fork. Feel free to take my changes or reject if they will not fit into the way you are using.
I am building with cabal inside of a larger project and I am using compile-proto-file to generate a clean haskell interface into a larger protocol buffer based ecosystem.
I am experiencing 2 issues which this pull request addresses:
1. When I try to install compile-proto-file using cabal, it complains about missing test modules which I fixed by adding an "autogenerated-modules" section to the cabal file.
1. All of the haskell files that compile-proto-file produces in my local build put the module name on the same line as the comment at the end of the header section so I added a …

Fix cabal build (for version 3.2) and add newline in generated haskell file

---

proto3-suite.cabal

- aeson: < 1.5 -> < 1.6
- base64-bytestring: < 1.1 -> < 1.2
- QuickCheck: < 2.14 -> < 2.15
(tested with `cabal test` in nix env)

Widen upper dependency bounds

---

proto3-suite.cabal

I want to extend this to generate stuff besides Haskell by using it as a library, but to do so I need access to the Internal module. I figured might as well expose the other two as well.

expose internal modules

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs

`ServiceOptions` have been slightly extended to support the max receive message
length channel arg, so we need to tweak code generation slightly.

proto3-suite 0.4.2.0: Track grpc-haskell-0.0.2.0 changes

---

proto3-suite.cabal

This is to prepare for a Hackage release
I'm downgrading the version in `proto3-suite.cabal` to 0.4.1 because we
never cut a 0.4.1 release to Hackage, yet.

Version 0.4.1

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/JSONPB.hs
tests/Main.hs

The swagger2 library is broken under recent versions of cabal and ghc, causing this library unusable.
This pull request import a flag to disable the swagger part conditionally.

Support disabling swagger conditionally.

---

proto3-suite.cabal

Based on https://github.com/haskell/cabal/issues/7348 it appears that
this is a misuse of autogen-modules and the simplest fix is to remove
the annotation.
The practical consequence of fixing this is that we will be able to
now upload `proto3-suite` to Hackage again.

Remove autogen-modules from `proto3-suite.cabal`

---

proto3-suite.cabal
src/Google/Protobuf/Timestamp.hs
tests/TestCodeGen.hs

This change adds a new Google.Protobuf.Timestamp module to
handle the custom RFC3339 encoding used for JSON.
Related #103

Add Well-Known Timestamp Type

---

default.nix
nix/overlays/haskell.nix
proto3-suite.cabal
shell.nix

I implemented this incorrectly in https://github.com/awakesecurity/proto3-suite/pull/159.
The `swagger` Cabal flag is enabled by default, so we need to specify
the negative version instead.

Fix incorrect `enableSwagger` behavior in Nix code

---

src/Proto3/Suite/Class.hs

Adds missing `Message` instances for wrapped types (primitives wrapped by messages in `wrappers.proto`), enabling the use of wrappers like so:
```proto
syntax = "proto3";
package foo;
import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
service Foo {
rpc Foo (google.protobuf.Empty) returns (google.protobuf.StringValue);
}
```

Add `Message` instances for wrapped types

---

nix/overlays/haskell.nix

Consistent speed up on `hydra-dev`, from 90s to 50s to rebuild `proto3-suite-boot` and enter the shell. Also ignores `gen`, `dist-newstyle`, etc. so those don't affect the shell's hash anymore.

Speed up entry into Nix shell

---

src/Proto3/Suite/DotProto/AST.hs
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Rendering.hs

It's a `proto2` feature (and this is `proto3-suite`), and our parser
doesn't look for it, so it never appears in the AST anyways.
Also, I'd value the ability to treat e.g. `Maybe ByteString` as a
`BytesValue` and not be uncertain whether it's actually a `optional
bytes`.

Remove `Optional` from Protobuf AST

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate/Swagger.hs

Notes:
- These `format` values are non-standard / incorrect Swagger, so they're hidden behind a flag (off by default).
- Replacing the original `instance ToSchema (OverrideToSchema ByteString)` is okay because [we don't have `optional` anymore](https://github.com/awakesecurity/proto3-suite/pull/165), therefore `Maybe ByteString` now unambiguously refers to `BytesValue`.
cc @natefaubion
Commits are atomic.

Use Swagger schema `format` to distinguish wrapper types from primitives

---

proto3-suite.cabal
src/Proto3/Suite/DhallPB.hs
src/Proto3/Suite/DotProto/Generate.hs
tests/ArbitraryGeneratedTestTypes.hs
tests/SimpleEncodeDotProto.hs

Fixes errors handling older versions of `dhall` introduced in https://github.com/awakesecurity/proto3-suite/pull/166 / https://github.com/awakesecurity/proto3-suite/commit/8f89bb860f40c52bf6ef354c9a1dbf5530e54350.

Fix `dhall`

---

src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Internal.hs
test-files/test_proto_leading_dot.proto
tests/TestCodeGen.hs

This PR changes the casing scheme applied to service methods in the code generator. Previously the code generator would take a protobuf service declaration such as
```protobuf
service MyService {
rpc DubiousMethodName(string) returns (string);
rpc dubiousMethodName(bool) returns (int);
}
```
and emit the following record 
```haskell
data MyService = MyService 
{ myServiceDubiousMethodName :: String -> String 
, myServiceDubiousMethodName :: Bool -> Int -- Name collision 
} 
```
The code generator no longer applies a casing-transformation on the first character of a service method name, this includes spans of capital letters prefixing the string. i.e. the code generator now emits `myServiceDubiousMethodName` and `myServicedubiousMethodName`. This change also includes documentation for the …

fix: change to prevent capitalization of prefixed service method names

---

proto3-suite.cabal
src/Proto3/Suite/JSONPB/Class.hs

Just requires a few bound relaxations and support for aeson >= 2.0

Support GHC 9.0.2

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs

This change is required for the matching change in grpc-haskell made here: https://github.com/awakesecurity/gRPC-haskell/pull/134.
Additionally, we bump the patch release version of `proto3-suite` to `0.4.3`.

Update codegen to add the `serverMaxMetadataSize` field to generated `ServiceOptions`

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Internal.hs
tests/Main.hs
tests/Test/Proto/Generate/Name.hs
tests/Test/Proto/Generate/Name/Gen.hs

This PR changes the way `compile-proto-file` handles generating valid Haskell module names from protobuf files, fixes issue #182.

Fix module renaming in `compile-proto-file`

---

src/Proto3/Suite/JSONPB/Class.hs

Specifically, about Data.Aeson.Encoding.Internal going unused
in Proto3.Suite.JSONPB.Class when using pre-2.0.0 aeson.

Eliminate an unused-import warning

---

tests/TestCodeGen.hs
tests/decode.sh
tests/encode.sh

But continue to disable the "leading dot" and "protoc plugin"
tests because these still do not build and without a better
understanding of their purpose I am not sure how to fix them.

Re-enable most tests using protoc for Python as a reference.

---

proto3-suite.cabal

proto3-wire has been released recently and is available on hackage.

Update pinning of proto3-wire to < 1.4.0

---

nix/overlays/haskell-packages.nix
nix/packages/turtle.nix
proto3-suite.cabal
src/Proto3/Suite/DotProto/AST.hs
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Internal.hs
src/Proto3/Suite/DotProto/Parsing.hs
src/Proto3/Suite/DotProto/Rendering.hs

This builds against the older versions of `turtle`, too, albeit
at the expense of several deprecation warnings.  Once we cut a
release with this fix we can do a second pass to fix all the
warnings, that way end users have a smooth migration path.

Build against `turtle-1.6.0`

---

nix/overlays/haskell-packages.nix
proto3-suite.cabal

While I'd like to update more before releasing this would be worthwhile to try to squeeze in.
This is a minor version since proto3-suite does not export the signatures affected by the breakage (although usually major implies major)

Support proto3-wire 1.4

---

.gitignore
proto3-suite.cabal

Otherwise cabal build fails when used in source-repository-package

specify autogen-modules

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs

This fixes a regression introduced in https://github.com/awakesecurity/proto3-suite/pull/200, and bumps the version in proto3-suite.cabal (which I thought I had inadvertently already done in another PR)

0.5.1 Release, with feeling

---

src/Proto3/Suite/DotProto/Generate.hs

Multiple .proto files add names to the google.protobuf package, so when excluding dependencies upon wrappers we must exclude based upon the Haskell module name rather than the .proto package name--otherwise we accidentally exclude imports of modules such as Google.Protobuf.Duration.

Fix bug in exclusion of wrappers import.

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/JSONPB/Class.hs
tests/TestCodeGen.hs
tools/compile-proto-file/Main.hs

Context: https://github.com/awakesecurity/proto3-suite/pull/19
AFAIK, the use of Data.Text.Lazy is infrequent in the current ecosystem.
Adding an ability to toggle between strict and lazy texts releases us from tedious impedance matching

compile-proto-file: add --text-type option to generate code using strict Text

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Internal.hs
src/Proto3/Suite/DotProto/Parsing.hs
src/Proto3/Suite/DotProto/Rendering.hs
src/Turtle/Compat.hs

These all relate to Turtle functions deprecated by turtle-1.6.
Eliminating the warnings seems to make doctest behave more predictably.
We could use -Wno-deprecations, but this change is more selective.

Eliminate a number of compiler warnings.

---

src/Turtle/Compat.hs

Missing "Turtle." qualification caused build failure on versions
of turtle before 1.6.

Bug fix in Turtle compatibility module.

---

proto3-suite.cabal
src/Proto3/Suite/DotProto/Parsing.hs
tests/Main.hs
tests/Test/Proto/Parse/Gen.hs
tests/Test/Proto/Parse/Option.hs

Fixes the parser for protobuf option identifiers to support qualified option names such as:
```protobuf
syntax = "proto3";
import "foo";
option (foo.boolean_option_name_file) = true;
```

Support parsing qualified option names.

---

tests/TestCodeGen.hs

It seems that attempting to use conditional compilation on doctests
of the Swagger format for fields of Google protobuf wrapper type
silently suppresses those tests.
This commit replaces such doctests with HUnit tests.

Fix tests of the Swagger schema of Google protobuf wrapper fields.

---

src/Proto3/Suite/DotProto/Parsing.hs
test-files/google/protobuf/descriptor.proto
test-files/test_proto_extend.proto
tests/Main.hs

This PR extends the proto3 parser to support parsing message extensions. Message extensions that are parsed are discarded for now (theres no way to represent message extensions in the current AST), but the parser will no longer produce a parse error "expecting enum" when `extend` is encountered.

Message extension parsing support.

---

.github/workflows/ci.yml

… because GitHub is browning out macOS 10.15 builds:
https://github.com/awakesecurity/proto3-suite/actions/runs/2747559977

Upgrade macOS version used in CI

---

src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Parsing.hs
src/no-swagger-wrapper-format/Proto3/Suite/DotProto/Generate/Swagger/Wrappers.hs

* Enabled FlexibleContexts in Proto3/Suite/DotProto/Generate/Swagger/Wrappers.hs
* Fixed generated code for `Qualified` DotProtoIdentifier

Fix build issues

---

.github/workflows/ci.yml
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Internal.hs

This change fixes the following failure with ghc-9.6.1:
```
proto3-suite> src/Proto3/Suite/DotProto/Internal.hs:83:13: error: [GHC-76037]
proto3-suite>     Not in scope: type constructor or class ‘MonadIO’
proto3-suite>     Suggested fixes:
proto3-suite>       • Perhaps use one of these:
proto3-suite>           ‘Turtle.MonadIO’ (imported from Turtle),
proto3-suite>           ‘Monad’ (imported from Prelude)
proto3-suite>       • Perhaps you want to add ‘MonadIO’ to the import list
proto3-suite>         in the import of ‘Turtle’
proto3-suite>         (src/Proto3/Suite/DotProto/Internal.hs:(46,1)-(47,50)).
proto3-suite>    |
proto3-suite> 83 | dieLines :: MonadIO m => Text -> m a
proto3-suite>    |             ^^^^^^^
```

Bring MonadIO into scope

---

src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Internal.hs

The proto compilation currently requires a package declaration. This PR allows compilation without package declarations thus making this implementation compatible with other language implementations.

Support proto files without a package declaration

---

.github/workflows/ci.yml

This PR upgrades to install-nix-action@v22 in CI. This fixes an environment issue that occurs during the "install Nix` step, see:
- The same fix for `proto3-wire`: https://github.com/awakesecurity/proto3-wire/pull/98
- The same fix for `gRPC-haskell`: https://github.com/awakesecurity/gRPC-haskell/pull/154

Upgrade CI to `install-nix-action@v22`

---

src/Proto3/Suite/DotProto/Generate.hs

When building without the swagger flag, this change fixes the following error:
src/Proto3/Suite/DotProto/Generate.hs:792:46: error: [GHC-39999]
• Could not deduce ‘Functor f0’ arising from a use of ‘<$>’
from the context: MonadError CompileError m

Fix compilation error when swagger is disabled

---

CHANGELOG.md
proto3-suite.cabal
src/Proto3/Suite/Types.hs

Modify "Eq (Enumerated a)" and "Ord (Enumerated a)" to identify "Enumerated (Right e)" with "Enumerated (Left (fromProtoEnum e))" because those two values encode to the same octet sequence.  They are already equivalent as arguments to "isDefault @(Enumerated e)".
Also increase the major version because this bug fix might break existing applications or test suites.

Fix bug in instance "Eq (Enumerated a)".

---

src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/JSONPB/Class.hs
src/Proto3/Suite/Tutorial.hs
tests/Main.hs
tests/TestCodeGen.hs

1. Actually run the doctests in "Tutorial.hs". This commit also updates those doctests to match current expected types and behavior.
2. Convert doctests in test-only code to ordinary unit tests because:
a. Because they are in test-only code they do not actually provide
any documentation despite being expressed as doctests, and
b. It seems that doctests tend to be fragile when upgrading GHC or
dependencies, especially the ones found in "TestCodeGen.hs".

Improve doctests

---

nix/overlays/haskell-packages.nix

The absence of "-flarge-records" is not enough because the "large-records" cabal flag is enabled by default.
This fix should improve the coverage of continuous integration tests for the proto3-suite repository.

Nix: if enableLargeRecords is false use -f-large-records

---

src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Generate/Syntax.hs

During encoding, we used to create a list of builders for the fields of a protobuf message and then make a call to mconcat on the message builder type.  But mconcat is recursive and therefore cannot be inlined as such, and GHC seems reluctant to perform beta reduction on known constructors such as (:) across module boundaries.
Therefore this commit switches from "mconcat [x, y, z]" to "mappend (mappend x y) z" (for example).  These appends are left associativity because the builder writes in reverse, starting with the rightmost field.

Avoid allocating intermediate field builder list.

---

src/Proto3/Suite/Class.hs
src/Proto3/Suite/DotProto/AST.hs
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Internal.hs
src/Proto3/Suite/DotProto/Parsing.hs
src/Proto3/Suite/DotProto/Rendering.hs
tools/canonicalize-proto-file/Main.hs

Minor change improving the AST by removing the `DotProtoEmptyField` constructor from the `DotProtoField`. This constructor complicated the AST and was needed nowhere.

Remove unnecessary `DotProtoEmptyField` constructor

---

src/Proto3/Suite/DotProto/Generate/Syntax.hs
test-files/test_proto_negative_enum.proto
tests/SimpleDecodeDotProto.hs
tests/SimpleEncodeDotProto.hs
tests/TestCodeGen.hs
tests/check_simple_dot_proto.py
tests/decode.sh
tests/encode.sh
tests/send_simple_dot_proto.py

Integer literal expressions also needed fixing,
not just integer literal patterns.
This commit also adds tests of negative enum codes
based on interoperability with generated Python.

Fix intE and add tests.

---

src/Proto3/Suite/DotProto/Generate/Syntax.hs
test-files/test_proto_negative_enum.proto
tests/SimpleDecodeDotProto.hs
tests/SimpleEncodeDotProto.hs
tests/TestCodeGen.hs
tests/check_simple_dot_proto.py
tests/decode.sh
tests/encode.sh
tests/send_simple_dot_proto.py

Fixes an issue where enums with negative field numbers were compiled to the field's conjugate in `toProtoEnumMay` pattern matches.

Fix generation of negative enum fields

---

proto3-suite.cabal
shell.nix
src/Proto3/Suite/DotProto/AST.hs
src/Proto3/Suite/DotProto/Parsing.hs
src/Proto3/Suite/DotProto/Rendering.hs
test-files/test_proto_empty_field.proto
tests/Main.hs
tests/Test/Proto/Generate/Name.hs
tests/Test/Proto/Parse.hs
tests/Test/Proto/Parse/Core.hs
tests/Test/Proto/Parse/Option.hs
tests/TestCodeGen.hs
tools/canonicalize-proto-file/Main.hs

This PR adds support for parsing and discarding empty statements in enumerations, messages, and services. As well, this PR removes the "empty" constructors in `DotProtoServicePart` and `DotProtoMessagePart` as they're no longer used. This PR resolves issue #257.

Support for empty statement

---

default.nix

This PR updates the default GHC version used in the `nix-shell.nix` and `default.nix` file from `ghc8107` to `ghc948`.

Update default `ghc8107` to `ghc948`

---

shell.nix

This is only a temporary fix for an issue we've been encountering with provisioning a Nix shell on `aarch64-darwin` with the `semaphore-compat` and `unix` packages. This is known issue and is documented here: https://github.com/NixOS/nixpkgs/issues/333921

Fix remove `cabal-install` from Nix shell `buildInputs`

---

src/Proto3/Suite/Form/Encode.hs
src/Proto3/Suite/Form/Encode/Core.hs
tests/Main.hs

Also add `Eq` and `Show` instances for `MessageEncoding`,
rename `cacheMessageEncoder` to `cacheMessageEncoding`,
add `cacheMessage`, and rename `cachedPrefix` to `cacheFields`.

Add access to octets in MessageEncoding.

---

README.md
src/Proto3/Suite/DotProto/Generate/Record.hs

Now that support for `large-records` has been dropped we don't need to mention it in the `README.md` or in Haskell modules.

Remove `large-records` from `README`

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
nix/overlays/haskell-packages.nix
proto3-suite.cabal
src/Proto3/Suite/DotProto/Generate.hs
src/Proto3/Suite/DotProto/Generate/Syntax.hs
src/Proto3/Suite/Form/Encode/Core.hs
src/Proto3/Suite/Haskell/Parser.hs
tests/Main.hs

This PR changes the dependency of `proto3-suite` from `ghc` to `ghc-lib-parser`. This resolves version conflicts with the system GHC and results in lighter dependencies.
When depending on `proto3-suite` in my project, I encountered the following issues:
- `proto3-suite` currently depends directly on the `ghc` package, which can conflict with the system GHC
- The `ghci` package issue is particularly notable - Hackage only provides GHC 8.x versions, causing problems when using GHC 9.x
- This causes `cabal build` to fail with errors like:
```
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] trying: proto3-suite-0.9.0 (user goal)
[__1] next goal: ghc (dependency of proto3-suite)
[__1] rejecting: ghc-9.12.1 (conflict: proto3-suite => ghc>=9.0 && <9.11)
[__1] trying: ghc-9.10.1
[__2] …
```

build: depend from `ghc` to `ghc-lib-parser`

---

src/Proto3/Suite/DotProto/Internal.hs
tests/Test/Proto/Interval.hs

`Proto3.Suite.DotProto.Internal.joinIntervals (0, 1) (2, 3 :: Int)` now correctly reduces to `Just (0, 3)` instead of to `Nothing`.
`Proto3.Suite.DotProto.Internal.normalizeIntervals [(0, 5), (1, 1), (3, 3 :: Int), (5, 5 :: Int)]` now correctly reduces to `[(0,5)]` instead of `[(0, 5), (3, 3), (5, 5)]`.

Fix bugs in interval merging.

---

CHANGELOG.md
src/Proto3/Suite/DotProto/AST.hs
src/Proto3/Suite/DotProto/Rendering.hs

This PR addresses issue #279 and relocates all `Pretty` instances for AST types to the `Proto3.Suite.DotProto.AST` module.

Relocate `Pretty` instances

---

CHANGELOG.md
proto3-suite.cabal
src/Proto3/Suite/Form/Encode.hs
src/Proto3/Suite/Form/Encode/Core.hs
tests/Main.hs
tests/SimpleEncodeDotProto.hs

v0.9.2:
* [BREAKING CHANGE in experimental module: Rename `toLazyByteString` to `messageEncoderToLazyByteString`.]
* [BREAKING CHANGE in experimental module: Rename `cacheMessage` to `messageCache`.]
* [BREAKING CHANGE in experimental module: Delete `Eq` instance for `MessageEncoding` because it is application-defined whether we should ignore field order during comparison.]
* Add `Show` instance for `MessageEncoder`.
* Add `messageEncoderToByteString` and `unsafeByteStringToMessageEncoder`.

Show MessageEncoder

---

CHANGELOG.md
proto3-suite.cabal
src/Proto3/Suite/Form/Encode.hs
src/Proto3/Suite/Form/Encode/Core.hs
tests/Main.hs
tests/Test/Proto/ToEncoder.hs

v0.9.3:
* [#284](https://github.com/awakesecurity/proto3-suite/pull/284) Delete Repeated.hs
* [BREAKING CHANGE in experimental module: Rename `Prefix` to `FieldsEncoder`, along with related functions.]
* [BREAKING CHANGE in experimental module: Rename `Fields` to `FieldsEncoding`, along with related functions.]
* Add instances of `FromJSON`, `FromJSONPB`, `ToJSON`, `ToJSONPB` for `MessageEncoding` and `MessageEncoder`.

JSON encoding of MessageEncoder, MessageEncoding

---

proto3-suite.cabal

For allow QuickCheck 2.15 and 2.16.

build: relax QuickCheck upper bound to <2.17
