nix/proto3-wire.nix, src/Proto3/Suite/Class.hs, stack.yaml
Updates `proto3-wire` gitrev to `4cf2f349cbf27ef36af28ae51e2712d6cf5f7723`.
=> Update proto3 wire ref

src/Proto3/Suite/DotProto/Generate.hs, tools/canonicalize-proto-file/Main.hs
Fixes the regression introduced by #43
=> Fix canonicalize-proto-file

.travis.yml, README.md, fetch-nixpkgs.nix, nixpkgs.json, release.nix
Build status for this PR here: https://travis-ci.org/awakesecurity/proto3-suite/
=> Enable Travis CI

src/Proto3/Suite/DotProto/Generate.hs
This updates the code-generation logic to use `MonadError` so that the same
utilities can be reused between `Either` and `ExceptT` without conversion
=> Replace `CompileResult` with `MonadError CompileError`

proto3-suite.cabal, src/Proto3/Suite/JSONPB/Class.hs
Also fix the comment for `optEmitNamedOneof`
=> Bump major version to 0.2.0.0

src/Proto3/Suite/DotProto/Rendering.hs, src/Proto3/Suite/Types.hs
These changes get the project compiling with GHC 8.4.3 and base-4.11. I haven't had a chance to try the tests yet.
=> Add GHC 8.4.3/base-4.11 Support

src/Proto3/Suite/Class.hs
This PR is necessary to stay compat with the changes merged to proto3-wire. Seq is moved to list because the overheads weren't buying us anything algorithmically important...
=> move seq to list to track proto3-wire

src/Proto3/Suite/DotProto/Generate.hs
Some instances are provided by default, and there is a command
line option to provide custom instances that replace those.
Previously, only instances that were defined outside of the data type
definition could be overridden.  Now the compiler will also replace
those instances mentioned in deriving clauses of data type definitions.
=> Scan deriving clause when customizing instances

proto3-suite.cabal
=> Relax version constraints for Stackage LTS 13.6

nix/dhall.nix, proto3-suite.cabal
We need to bump the dhall dep to open up use of megaparsec-7.
=> bump dhall dep

src/Proto3/Suite/Class.hs
fix error introduced in 4007fd0351a0629174da656fa02ecd76fac965eb
=> fix unbound variable

release.nix
=> Disable `dhall`'s test suite

nix/fetchNixpkgs.nix, nix/proto3-wire.nix, proto3-suite.cabal, release.nix, src/Proto3/Suite/Class.hs
Also raise the minimum GHC version to 8.6 and
drop support for Nix versions prior to 1.12.
=> Upgrade to proto3-wire 1.2.0.

src/Proto3/Suite/DotProto/Generate/Swagger.hs
Fixes https://github.com/awakesecurity/proto3-suite/issues/119
=> Add `ToSchema` instance for `Map k ByteString`

proto3-suite.cabal
Fixes https://github.com/awakesecurity/proto3-suite/issues/154
=> Increase upper bound on `tasty`

stack.yaml
See https://www.fpcomplete.com/blog/2017/07/stacks-new-extensible-snapshots/
=> Update stack.yaml to be compatible with latest stack versions

.github/workflows/ci.yml, default.nix, nix/overlays/haskell.nix, nix/pkgs.nix, shell.nix
=> More Nix refactoring

default.nix, nix/overlays/haskell-packages.nix, nix/pkgs.nix, proto3-suite.cabal, shell.nix, src/Proto3/Suite/DotProto/Generate/Swagger.hs, src/Proto3/Suite/DotProto/Generate/Swagger.hs-boot, src/Proto3/Suite/DotProto/Generate/Swagger/Wrappers.hs, src/no-swagger-wrapper-format/Proto3/Suite/DotProto/Generate/Swagger/Wrappers.hs, src/swagger-wrapper-format/Proto3/Suite/DotProto/Generate/Swagger/Wrappers.hs
=> Reduce use of `-XCPP` for conditional compilation

src/Google/Protobuf/Timestamp.hs
=> Fix build with -f-swagger

CHANGELOG.md, proto3-suite.cabal
Fixes https://github.com/awakesecurity/proto3-suite/issues/189
=> Version 0.5.0

tests/TestCodeGen.hs
Has been replaced by an HUnit test.
=> Eliminate leftover doctest.

nix/overlays/haskell-packages.nix, src/Proto3/Suite/Class.hs
...at the cost of some increased code size.
=> Encode field numbers at compile time

src/Proto3/Suite/DotProto/Parsing.hs, src/Proto3/Suite/DotProto/Rendering.hs, tools/canonicalize-proto-file/Main.hs
Fixes some small issues that were merged in with #265.
=> Fix canonicalize for reserved enum fields
